let firstFavNumb = 21;
let secondFavNumb = 6;
console.log(firstFavNumb<secondFavNumb);
console.log(firstFavNumb>secondFavNumb);
console.log(firstFavNumb<=secondFavNumb);
console.log(firstFavNumb>=secondFavNumb);
console.log(firstFavNumb===secondFavNumb);
console.log(firstFavNumb==secondFavNumb);
console.log(firstFavNumb!==secondFavNumb);
console.log(firstFavNumb!=secondFavNumb);
console.log(power);